### PR TITLE
remove clips

### PR DESCRIPTION
**Pull request by adeebshihadeh**

### CODE REVIEW

**Comment by devtekve** [comment]
Why was this done? is there any some context regarding this ? Thanks :)

**Comment by adeebshihadeh** [comment]
It's a good feature, but we removed it because this implementation was buggy and needs to be rewritten. We'll bring it back once we can do it well.

**Comment by devtekve** [comment]
Thanks for sharing!

**Comment by joeysantana3** [comment]
Hi @adeebshihadeh. Today I just realized I lost clip functionality. My primary use case for comma prime is the clip feature. I can understand it being buggy, but it did work (at least for me). Was there another motivation for removing this besides it just being buggy? Was the “bugginess” of this feature causing issues in different parts of the app? I’m just wondering if it can be brought back as it seems this was an unpopular decision amongst comma prime users. For me, $24 a month for comma prime isn’t worth it without clips. Thanks for any info you can provide.

**Pull request merged**
