### PR TITLE
navigate to coordinates endpoint

### PR DESCRIPTION
**Pull request by fredyshox**
Prototype of `/navigate?lat=LAT&long=LONG` route, which triggers navigation prompt to specified coordinates for current dongle id.

### CODE REVIEW

**Comment by gregjhogan** [comment]
Android can support this nicely via PWA manifest [share_target](https://developer.mozilla.org/en-US/docs/Web/Manifest/share_target) with the addition of making a `HEAD` request to the URL passed in to get the lat/long of the shared location (and the name of the place selected if you selected a location with a name in google maps).

**Comment by fredyshox** [comment]
That's the goal :+1:  It's slightly more complicated on iOS, because it would need custom [Shortcut](https://support.apple.com/guide/shortcuts/welcome/ios) to appear in the share sheet, but it's definitely doable.

**Comment by fredyshox** [comment]
CORS prevents me from expanding shortened gmaps url using HEAD request. Will probably need additional endpoint on backend side for that.

**Comment by gregjhogan** [comment]
That is annoying, you could probably use a hidden iframe to load the URL and inspect it instead, but a new back end API endpoint may be better (may even want to use the google maps API instead of a head request).  Also, I think your url parsing for google maps is extracting the center of the map and not the coordinates of the place?

**Pull request closed without merging**
