### PR TITLE
add styling to make hyperlinks more obvious

### PR DESCRIPTION
**Pull request by BBBmau**
Was going through connect and never realized that both `FAQ` and `shop` are hyperlinks on the Checkout page

This PR just adds styling on them so that they're more obvious to users.

Before:
Screenshot 2024-05-16 at 3 18 41 PM

After:
Screenshot 2024-05-16 at 3 18 41 PM

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Nice improvement. Let's also do an underline?

**Comment by BBBmau** [comment]
@adeebshihadeh underline is added



image

**Comment by BBBmau** [comment]
latest commit has the recent geocode change

**Comment by BBBmau** [comment]
test failure is the same as: 0216a272064c202e15a13283358d1f28543f60d6

**Comment by adeebshihadeh** [comment]
Nice improvement!

**Pull request merged**
