### PR TITLE
clips: improve sharing buttons

### PR DESCRIPTION
**Pull request by incognitojam**
- Move share button to bottom row and make clip public when pressed

<table>
<tr><th></th><th>Private</th><th>Public</th></tr>
<tr><td>New</td><td>

</td><td>

</td></tr>
<tr><td>Old</td><td>

</td><td>

</td></tr></table>

Related:  #261

### CODE REVIEW

**Comment by adeebshihadeh** [comment]
Hmm, I think this is still a bit confusing. How about a public/private toggle and the share button flips the toggle to public?

**Comment by incognitojam** [comment]
New:
<table><tr><th>Private</th><th>Public</th></tr>
<tr><td>

</td><td>

</td></tr>
</table>

**Comment by adeebshihadeh** [comment]
Oh, I meant let's make it look like a slider toggle too (like the preserve button). It's not really clear it's a toggle right now.

**Comment by incognitojam** [comment]
Oh okay I was just going to ask that

**Comment by incognitojam** [comment]
New:
|Private|Public|
|-|-|
|Screenshot from 2022-09-27 17-31-42|Screenshot from 2022-09-27 17-31-49|

Clicking share causes private to change to public, or you can toggle the switch manually

**Comment by adeebshihadeh** [comment]
LGTM

**Pull request merged**
